//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace InterfaceUsuario.ServicoAtributo {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicoAtributoSoap", Namespace="http://www.pece.org.br/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResponse))]
    public partial class ServicoAtributo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CriarAtributoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarAtributoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarAtributoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarAtributoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarAtributosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAtributosDisponiveisOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAtributosTipoPatrimonioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAtributosPorPatrimonioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicoAtributo() {
            this.Url = global::InterfaceUsuario.Properties.Settings.Default.InterfaceUsuario_ServicoAtributo_ServicoAtributo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CriarAtributoCompletedEventHandler CriarAtributoCompleted;
        
        /// <remarks/>
        public event DeletarAtributoCompletedEventHandler DeletarAtributoCompleted;
        
        /// <remarks/>
        public event AlterarAtributoCompletedEventHandler AlterarAtributoCompleted;
        
        /// <remarks/>
        public event ConsultarAtributoCompletedEventHandler ConsultarAtributoCompleted;
        
        /// <remarks/>
        public event BuscarAtributosCompletedEventHandler BuscarAtributosCompleted;
        
        /// <remarks/>
        public event ListarAtributosDisponiveisCompletedEventHandler ListarAtributosDisponiveisCompleted;
        
        /// <remarks/>
        public event ListarAtributosTipoPatrimonioCompletedEventHandler ListarAtributosTipoPatrimonioCompleted;
        
        /// <remarks/>
        public event ListarAtributosPorPatrimonioCompletedEventHandler ListarAtributosPorPatrimonioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/CriaAtributo", RequestElementName="CriaAtributo", RequestNamespace="http://www.pece.org.br/", ResponseElementName="CriaAtributoResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseAtributo", IsNullable=true)]
        public ResponseAtributo CriarAtributo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestAtributo RequestAtributo) {
            object[] results = this.Invoke("CriarAtributo", new object[] {
                        RequestAtributo});
            return ((ResponseAtributo)(results[0]));
        }
        
        /// <remarks/>
        public void CriarAtributoAsync(RequestAtributo RequestAtributo) {
            this.CriarAtributoAsync(RequestAtributo, null);
        }
        
        /// <remarks/>
        public void CriarAtributoAsync(RequestAtributo RequestAtributo, object userState) {
            if ((this.CriarAtributoOperationCompleted == null)) {
                this.CriarAtributoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCriarAtributoOperationCompleted);
            }
            this.InvokeAsync("CriarAtributo", new object[] {
                        RequestAtributo}, this.CriarAtributoOperationCompleted, userState);
        }
        
        private void OnCriarAtributoOperationCompleted(object arg) {
            if ((this.CriarAtributoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CriarAtributoCompleted(this, new CriarAtributoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/DeletaAtributo", RequestElementName="DeletaAtributo", RequestNamespace="http://www.pece.org.br/", ResponseElementName="DeletaAtributoResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseAtributo", IsNullable=true)]
        public ResponseAtributo DeletarAtributo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestAtributo RequestAtributo) {
            object[] results = this.Invoke("DeletarAtributo", new object[] {
                        RequestAtributo});
            return ((ResponseAtributo)(results[0]));
        }
        
        /// <remarks/>
        public void DeletarAtributoAsync(RequestAtributo RequestAtributo) {
            this.DeletarAtributoAsync(RequestAtributo, null);
        }
        
        /// <remarks/>
        public void DeletarAtributoAsync(RequestAtributo RequestAtributo, object userState) {
            if ((this.DeletarAtributoOperationCompleted == null)) {
                this.DeletarAtributoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarAtributoOperationCompleted);
            }
            this.InvokeAsync("DeletarAtributo", new object[] {
                        RequestAtributo}, this.DeletarAtributoOperationCompleted, userState);
        }
        
        private void OnDeletarAtributoOperationCompleted(object arg) {
            if ((this.DeletarAtributoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarAtributoCompleted(this, new DeletarAtributoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/AlteraAtributo", RequestElementName="AlteraAtributo", RequestNamespace="http://www.pece.org.br/", ResponseElementName="AlteraAtributoResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseAtributo", IsNullable=true)]
        public ResponseAtributo AlterarAtributo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestAtributo RequestAtributo) {
            object[] results = this.Invoke("AlterarAtributo", new object[] {
                        RequestAtributo});
            return ((ResponseAtributo)(results[0]));
        }
        
        /// <remarks/>
        public void AlterarAtributoAsync(RequestAtributo RequestAtributo) {
            this.AlterarAtributoAsync(RequestAtributo, null);
        }
        
        /// <remarks/>
        public void AlterarAtributoAsync(RequestAtributo RequestAtributo, object userState) {
            if ((this.AlterarAtributoOperationCompleted == null)) {
                this.AlterarAtributoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarAtributoOperationCompleted);
            }
            this.InvokeAsync("AlterarAtributo", new object[] {
                        RequestAtributo}, this.AlterarAtributoOperationCompleted, userState);
        }
        
        private void OnAlterarAtributoOperationCompleted(object arg) {
            if ((this.AlterarAtributoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarAtributoCompleted(this, new AlterarAtributoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/ConsultaAtributo", RequestElementName="ConsultaAtributo", RequestNamespace="http://www.pece.org.br/", ResponseElementName="ConsultaAtributoResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseAtributo", IsNullable=true)]
        public ResponseAtributo ConsultarAtributo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestAtributo RequestAtributo) {
            object[] results = this.Invoke("ConsultarAtributo", new object[] {
                        RequestAtributo});
            return ((ResponseAtributo)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarAtributoAsync(RequestAtributo RequestAtributo) {
            this.ConsultarAtributoAsync(RequestAtributo, null);
        }
        
        /// <remarks/>
        public void ConsultarAtributoAsync(RequestAtributo RequestAtributo, object userState) {
            if ((this.ConsultarAtributoOperationCompleted == null)) {
                this.ConsultarAtributoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarAtributoOperationCompleted);
            }
            this.InvokeAsync("ConsultarAtributo", new object[] {
                        RequestAtributo}, this.ConsultarAtributoOperationCompleted, userState);
        }
        
        private void OnConsultarAtributoOperationCompleted(object arg) {
            if ((this.ConsultarAtributoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarAtributoCompleted(this, new ConsultarAtributoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/BuscaAtributos", RequestElementName="BuscaAtributos", RequestNamespace="http://www.pece.org.br/", ResponseElementName="BuscaAtributosResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseAtributo", IsNullable=true)]
        public ResponseAtributo BuscarAtributos([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestAtributo RequestAtributo) {
            object[] results = this.Invoke("BuscarAtributos", new object[] {
                        RequestAtributo});
            return ((ResponseAtributo)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarAtributosAsync(RequestAtributo RequestAtributo) {
            this.BuscarAtributosAsync(RequestAtributo, null);
        }
        
        /// <remarks/>
        public void BuscarAtributosAsync(RequestAtributo RequestAtributo, object userState) {
            if ((this.BuscarAtributosOperationCompleted == null)) {
                this.BuscarAtributosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarAtributosOperationCompleted);
            }
            this.InvokeAsync("BuscarAtributos", new object[] {
                        RequestAtributo}, this.BuscarAtributosOperationCompleted, userState);
        }
        
        private void OnBuscarAtributosOperationCompleted(object arg) {
            if ((this.BuscarAtributosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarAtributosCompleted(this, new BuscarAtributosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/ListarAtributosDisponiveis", RequestNamespace="http://www.pece.org.br/", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseAtributo", IsNullable=true)]
        public ResponseAtributo ListarAtributosDisponiveis([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestAtributo RequestAtributo) {
            object[] results = this.Invoke("ListarAtributosDisponiveis", new object[] {
                        RequestAtributo});
            return ((ResponseAtributo)(results[0]));
        }
        
        /// <remarks/>
        public void ListarAtributosDisponiveisAsync(RequestAtributo RequestAtributo) {
            this.ListarAtributosDisponiveisAsync(RequestAtributo, null);
        }
        
        /// <remarks/>
        public void ListarAtributosDisponiveisAsync(RequestAtributo RequestAtributo, object userState) {
            if ((this.ListarAtributosDisponiveisOperationCompleted == null)) {
                this.ListarAtributosDisponiveisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAtributosDisponiveisOperationCompleted);
            }
            this.InvokeAsync("ListarAtributosDisponiveis", new object[] {
                        RequestAtributo}, this.ListarAtributosDisponiveisOperationCompleted, userState);
        }
        
        private void OnListarAtributosDisponiveisOperationCompleted(object arg) {
            if ((this.ListarAtributosDisponiveisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAtributosDisponiveisCompleted(this, new ListarAtributosDisponiveisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/ListarAtributosTipoPatrimonio", RequestNamespace="http://www.pece.org.br/", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseAtributo", IsNullable=true)]
        public ResponseAtributo ListarAtributosTipoPatrimonio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestTipoPatrimonio RequestTipoPatrimonio) {
            object[] results = this.Invoke("ListarAtributosTipoPatrimonio", new object[] {
                        RequestTipoPatrimonio});
            return ((ResponseAtributo)(results[0]));
        }
        
        /// <remarks/>
        public void ListarAtributosTipoPatrimonioAsync(RequestTipoPatrimonio RequestTipoPatrimonio) {
            this.ListarAtributosTipoPatrimonioAsync(RequestTipoPatrimonio, null);
        }
        
        /// <remarks/>
        public void ListarAtributosTipoPatrimonioAsync(RequestTipoPatrimonio RequestTipoPatrimonio, object userState) {
            if ((this.ListarAtributosTipoPatrimonioOperationCompleted == null)) {
                this.ListarAtributosTipoPatrimonioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAtributosTipoPatrimonioOperationCompleted);
            }
            this.InvokeAsync("ListarAtributosTipoPatrimonio", new object[] {
                        RequestTipoPatrimonio}, this.ListarAtributosTipoPatrimonioOperationCompleted, userState);
        }
        
        private void OnListarAtributosTipoPatrimonioOperationCompleted(object arg) {
            if ((this.ListarAtributosTipoPatrimonioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAtributosTipoPatrimonioCompleted(this, new ListarAtributosTipoPatrimonioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/ListarAtributosPorPatrimonio", RequestNamespace="http://www.pece.org.br/", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseAtributo", IsNullable=true)]
        public ResponseAtributo ListarAtributosPorPatrimonio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestPatrimonio RequestPatrimonio) {
            object[] results = this.Invoke("ListarAtributosPorPatrimonio", new object[] {
                        RequestPatrimonio});
            return ((ResponseAtributo)(results[0]));
        }
        
        /// <remarks/>
        public void ListarAtributosPorPatrimonioAsync(RequestPatrimonio RequestPatrimonio) {
            this.ListarAtributosPorPatrimonioAsync(RequestPatrimonio, null);
        }
        
        /// <remarks/>
        public void ListarAtributosPorPatrimonioAsync(RequestPatrimonio RequestPatrimonio, object userState) {
            if ((this.ListarAtributosPorPatrimonioOperationCompleted == null)) {
                this.ListarAtributosPorPatrimonioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAtributosPorPatrimonioOperationCompleted);
            }
            this.InvokeAsync("ListarAtributosPorPatrimonio", new object[] {
                        RequestPatrimonio}, this.ListarAtributosPorPatrimonioOperationCompleted, userState);
        }
        
        private void OnListarAtributosPorPatrimonioOperationCompleted(object arg) {
            if ((this.ListarAtributosPorPatrimonioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAtributosPorPatrimonioCompleted(this, new ListarAtributosPorPatrimonioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class RequestAtributo {
        
        private Atributo atributoField;
        
        private int idAtributoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Atributo Atributo {
            get {
                return this.atributoField;
            }
            set {
                this.atributoField = value;
            }
        }
        
        /// <remarks/>
        public int IdAtributo {
            get {
                return this.idAtributoField;
            }
            set {
                this.idAtributoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Atributo {
        
        private int idField;
        
        private string nomeField;
        
        private string descricaoField;
        
        private string tipoField;
        
        private bool nuloField;
        
        private string[] listaValoresField;
        
        private string valorField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public bool Nulo {
            get {
                return this.nuloField;
            }
            set {
                this.nuloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ListaValores")]
        public string[] ListaValores {
            get {
                return this.listaValoresField;
            }
            set {
                this.listaValoresField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Busca {
        
        private int idEquipamentoField;
        
        private System.DateTime dtCompraMinField;
        
        private System.DateTime dtCompraMaxField;
        
        private int numeroNotaFiscalField;
        
        private System.DateTime dtExpGarantiaMinField;
        
        private System.DateTime dtExpGarantiaMaxField;
        
        private int idTipoPatrimonioField;
        
        private string caminhoFotoNotaFiscalField;
        
        private string caminhoFotoPatrimonioField;
        
        private int numeroPeceField;
        
        private string numeroPedidoField;
        
        private string localField;
        
        /// <remarks/>
        public int IdEquipamento {
            get {
                return this.idEquipamentoField;
            }
            set {
                this.idEquipamentoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtCompraMin {
            get {
                return this.dtCompraMinField;
            }
            set {
                this.dtCompraMinField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtCompraMax {
            get {
                return this.dtCompraMaxField;
            }
            set {
                this.dtCompraMaxField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroNotaFiscal {
            get {
                return this.numeroNotaFiscalField;
            }
            set {
                this.numeroNotaFiscalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtExpGarantiaMin {
            get {
                return this.dtExpGarantiaMinField;
            }
            set {
                this.dtExpGarantiaMinField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtExpGarantiaMax {
            get {
                return this.dtExpGarantiaMaxField;
            }
            set {
                this.dtExpGarantiaMaxField = value;
            }
        }
        
        /// <remarks/>
        public int IdTipoPatrimonio {
            get {
                return this.idTipoPatrimonioField;
            }
            set {
                this.idTipoPatrimonioField = value;
            }
        }
        
        /// <remarks/>
        public string CaminhoFotoNotaFiscal {
            get {
                return this.caminhoFotoNotaFiscalField;
            }
            set {
                this.caminhoFotoNotaFiscalField = value;
            }
        }
        
        /// <remarks/>
        public string CaminhoFotoPatrimonio {
            get {
                return this.caminhoFotoPatrimonioField;
            }
            set {
                this.caminhoFotoPatrimonioField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroPece {
            get {
                return this.numeroPeceField;
            }
            set {
                this.numeroPeceField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroPedido {
            get {
                return this.numeroPedidoField;
            }
            set {
                this.numeroPedidoField = value;
            }
        }
        
        /// <remarks/>
        public string Local {
            get {
                return this.localField;
            }
            set {
                this.localField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Baixa {
        
        private int idBaixaField;
        
        private System.DateTime dataManutencaoField;
        
        private string destinoBaixaField;
        
        private string observacoesBaixaField;
        
        private int idUsuarioField;
        
        /// <remarks/>
        public int IdBaixa {
            get {
                return this.idBaixaField;
            }
            set {
                this.idBaixaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataManutencao {
            get {
                return this.dataManutencaoField;
            }
            set {
                this.dataManutencaoField = value;
            }
        }
        
        /// <remarks/>
        public string DestinoBaixa {
            get {
                return this.destinoBaixaField;
            }
            set {
                this.destinoBaixaField = value;
            }
        }
        
        /// <remarks/>
        public string ObservacoesBaixa {
            get {
                return this.observacoesBaixaField;
            }
            set {
                this.observacoesBaixaField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Manutencao {
        
        private int idManutencaoField;
        
        private System.DateTime dataManutencaoField;
        
        private string motivoField;
        
        private string observacaoField;
        
        private int idUsuarioField;
        
        private int idPatrimonioField;
        
        /// <remarks/>
        public int IdManutencao {
            get {
                return this.idManutencaoField;
            }
            set {
                this.idManutencaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataManutencao {
            get {
                return this.dataManutencaoField;
            }
            set {
                this.dataManutencaoField = value;
            }
        }
        
        /// <remarks/>
        public string Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        public string Observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public int IdPatrimonio {
            get {
                return this.idPatrimonioField;
            }
            set {
                this.idPatrimonioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Patrimonio {
        
        private int idEquipamentoField;
        
        private int numeroPECEField;
        
        private System.DateTime dataCompraField;
        
        private int numeroNotaFiscalField;
        
        private System.DateTime dataExpGarantiaField;
        
        private Atributo[] listAtributosField;
        
        private string caminhoFotoNotaFiscalField;
        
        private string caminhoFotoPatrimonioField;
        
        private string localPatrimonioField;
        
        private string numeroPedidoField;
        
        private int idTipoPatrimonioField;
        
        /// <remarks/>
        public int IdEquipamento {
            get {
                return this.idEquipamentoField;
            }
            set {
                this.idEquipamentoField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroPECE {
            get {
                return this.numeroPECEField;
            }
            set {
                this.numeroPECEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataCompra {
            get {
                return this.dataCompraField;
            }
            set {
                this.dataCompraField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroNotaFiscal {
            get {
                return this.numeroNotaFiscalField;
            }
            set {
                this.numeroNotaFiscalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataExpGarantia {
            get {
                return this.dataExpGarantiaField;
            }
            set {
                this.dataExpGarantiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ListAtributos")]
        public Atributo[] ListAtributos {
            get {
                return this.listAtributosField;
            }
            set {
                this.listAtributosField = value;
            }
        }
        
        /// <remarks/>
        public string CaminhoFotoNotaFiscal {
            get {
                return this.caminhoFotoNotaFiscalField;
            }
            set {
                this.caminhoFotoNotaFiscalField = value;
            }
        }
        
        /// <remarks/>
        public string CaminhoFotoPatrimonio {
            get {
                return this.caminhoFotoPatrimonioField;
            }
            set {
                this.caminhoFotoPatrimonioField = value;
            }
        }
        
        /// <remarks/>
        public string LocalPatrimonio {
            get {
                return this.localPatrimonioField;
            }
            set {
                this.localPatrimonioField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroPedido {
            get {
                return this.numeroPedidoField;
            }
            set {
                this.numeroPedidoField = value;
            }
        }
        
        /// <remarks/>
        public int IdTipoPatrimonio {
            get {
                return this.idTipoPatrimonioField;
            }
            set {
                this.idTipoPatrimonioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class RequestPatrimonio {
        
        private Patrimonio patrimonioField;
        
        private Manutencao manutencaoField;
        
        private Baixa baixaPatrimonioField;
        
        private Busca buscaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Patrimonio Patrimonio {
            get {
                return this.patrimonioField;
            }
            set {
                this.patrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Manutencao Manutencao {
            get {
                return this.manutencaoField;
            }
            set {
                this.manutencaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Baixa BaixaPatrimonio {
            get {
                return this.baixaPatrimonioField;
            }
            set {
                this.baixaPatrimonioField = value;
            }
        }
        
        /// <remarks/>
        public Busca Busca {
            get {
                return this.buscaField;
            }
            set {
                this.buscaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class TipoPatrimonio {
        
        private int idField;
        
        private string nomeField;
        
        private string descricaoField;
        
        private Atributo[] listAtributosField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ListAtributos")]
        public Atributo[] ListAtributos {
            get {
                return this.listAtributosField;
            }
            set {
                this.listAtributosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class RequestTipoPatrimonio {
        
        private TipoPatrimonio tipoPatrimonioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TipoPatrimonio TipoPatrimonio {
            get {
                return this.tipoPatrimonioField;
            }
            set {
                this.tipoPatrimonioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseAtributo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class BaseResponse {
        
        private ResponseStatus statusCodeField;
        
        private string messageField;
        
        /// <remarks/>
        public ResponseStatus StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public enum ResponseStatus {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        NoContent,
        
        /// <remarks/>
        MovedPermanently,
        
        /// <remarks/>
        Found,
        
        /// <remarks/>
        SeeOther,
        
        /// <remarks/>
        NotModified,
        
        /// <remarks/>
        BadRequest,
        
        /// <remarks/>
        Unauthorized,
        
        /// <remarks/>
        Forbidden,
        
        /// <remarks/>
        NotFound,
        
        /// <remarks/>
        MethodNotAllowed,
        
        /// <remarks/>
        RequestTimeout,
        
        /// <remarks/>
        Conflict,
        
        /// <remarks/>
        NotImplemented,
        
        /// <remarks/>
        ServiceUnavailable,
        
        /// <remarks/>
        BadVersion,
        
        /// <remarks/>
        InternalServerError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class ResponseAtributo : BaseResponse {
        
        private Atributo[] listaAtributosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Atributo[] ListaAtributos {
            get {
                return this.listaAtributosField;
            }
            set {
                this.listaAtributosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CriarAtributoCompletedEventHandler(object sender, CriarAtributoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CriarAtributoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CriarAtributoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseAtributo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseAtributo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void DeletarAtributoCompletedEventHandler(object sender, DeletarAtributoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletarAtributoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletarAtributoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseAtributo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseAtributo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void AlterarAtributoCompletedEventHandler(object sender, AlterarAtributoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlterarAtributoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlterarAtributoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseAtributo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseAtributo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ConsultarAtributoCompletedEventHandler(object sender, ConsultarAtributoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarAtributoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarAtributoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseAtributo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseAtributo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void BuscarAtributosCompletedEventHandler(object sender, BuscarAtributosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarAtributosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarAtributosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseAtributo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseAtributo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ListarAtributosDisponiveisCompletedEventHandler(object sender, ListarAtributosDisponiveisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAtributosDisponiveisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAtributosDisponiveisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseAtributo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseAtributo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ListarAtributosTipoPatrimonioCompletedEventHandler(object sender, ListarAtributosTipoPatrimonioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAtributosTipoPatrimonioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAtributosTipoPatrimonioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseAtributo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseAtributo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ListarAtributosPorPatrimonioCompletedEventHandler(object sender, ListarAtributosPorPatrimonioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAtributosPorPatrimonioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAtributosPorPatrimonioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseAtributo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseAtributo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591