//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceUsuario.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1165/TipoPatrimonio/ServicoTipoPatrimonio.asmx")]
        public string InterfaceUsuario_ServicoTipoPatrimonio_ServicoTipoPatrimonio {
            get {
                return ((string)(this["InterfaceUsuario_ServicoTipoPatrimonio_ServicoTipoPatrimonio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1180/Autenticador/ServicoAutenticador.asmx")]
        public string InterfaceUsuario_ServicoAutenticador_ServicoAutenticador {
            get {
                return ((string)(this["InterfaceUsuario_ServicoAutenticador_ServicoAutenticador"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1165/Relatorio/ServicoRelatorio.asmx")]
        public string InterfaceUsuario_ServicoRelatorio_ServicoRelatorio {
            get {
                return ((string)(this["InterfaceUsuario_ServicoRelatorio_ServicoRelatorio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1180/Usuario/ServicoUsuario.asmx")]
        public string InterfaceUsuario_ServicoUsuario_ServicoUsuario {
            get {
                return ((string)(this["InterfaceUsuario_ServicoUsuario_ServicoUsuario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1165/Patrimonio/ServicoPatrimonio.asmx")]
        public string InterfaceUsuario_ServicoPatrimonio_ServicoPatrimonio {
            get {
                return ((string)(this["InterfaceUsuario_ServicoPatrimonio_ServicoPatrimonio"]));
            }
        }
    }
}
