//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace InterfaceUsuario.ServicoTipoPatrimonio {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicoTipoPatrimonioSoap", Namespace="http://www.pece.org.br/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResponse))]
    public partial class ServicoTipoPatrimonio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CriarTipoPatrimonioOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarTipoPatrimonioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarTipoPatrimonioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarTipoPatrimonioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicoTipoPatrimonio() {
            this.Url = global::InterfaceUsuario.Properties.Settings.Default.InterfaceUsuario_ServicoTipoPatrimonio_ServicoTipoPatrimonio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CriarTipoPatrimonioCompletedEventHandler CriarTipoPatrimonioCompleted;
        
        /// <remarks/>
        public event DeletarTipoPatrimonioCompletedEventHandler DeletarTipoPatrimonioCompleted;
        
        /// <remarks/>
        public event AlterarTipoPatrimonioCompletedEventHandler AlterarTipoPatrimonioCompleted;
        
        /// <remarks/>
        public event ConsultarTipoPatrimonioCompletedEventHandler ConsultarTipoPatrimonioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/CriaTipoPatrimonio", RequestElementName="CriaTipoPatrimonio", RequestNamespace="http://www.pece.org.br/", ResponseElementName="CriaTipoPatrimonioResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseTipoPatrimonio", IsNullable=true)]
        public ResponseTipoPatrimonio CriarTipoPatrimonio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestTipoPatrimonio RequestTipoPatrimonio) {
            object[] results = this.Invoke("CriarTipoPatrimonio", new object[] {
                        RequestTipoPatrimonio});
            return ((ResponseTipoPatrimonio)(results[0]));
        }
        
        /// <remarks/>
        public void CriarTipoPatrimonioAsync(RequestTipoPatrimonio RequestTipoPatrimonio) {
            this.CriarTipoPatrimonioAsync(RequestTipoPatrimonio, null);
        }
        
        /// <remarks/>
        public void CriarTipoPatrimonioAsync(RequestTipoPatrimonio RequestTipoPatrimonio, object userState) {
            if ((this.CriarTipoPatrimonioOperationCompleted == null)) {
                this.CriarTipoPatrimonioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCriarTipoPatrimonioOperationCompleted);
            }
            this.InvokeAsync("CriarTipoPatrimonio", new object[] {
                        RequestTipoPatrimonio}, this.CriarTipoPatrimonioOperationCompleted, userState);
        }
        
        private void OnCriarTipoPatrimonioOperationCompleted(object arg) {
            if ((this.CriarTipoPatrimonioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CriarTipoPatrimonioCompleted(this, new CriarTipoPatrimonioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/DeletaTipoPatrimonio", RequestElementName="DeletaTipoPatrimonio", RequestNamespace="http://www.pece.org.br/", ResponseElementName="DeletaTipoPatrimonioResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseTipoPatrimonio", IsNullable=true)]
        public ResponseTipoPatrimonio DeletarTipoPatrimonio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestTipoPatrimonio RequestTipoPatrimonio) {
            object[] results = this.Invoke("DeletarTipoPatrimonio", new object[] {
                        RequestTipoPatrimonio});
            return ((ResponseTipoPatrimonio)(results[0]));
        }
        
        /// <remarks/>
        public void DeletarTipoPatrimonioAsync(RequestTipoPatrimonio RequestTipoPatrimonio) {
            this.DeletarTipoPatrimonioAsync(RequestTipoPatrimonio, null);
        }
        
        /// <remarks/>
        public void DeletarTipoPatrimonioAsync(RequestTipoPatrimonio RequestTipoPatrimonio, object userState) {
            if ((this.DeletarTipoPatrimonioOperationCompleted == null)) {
                this.DeletarTipoPatrimonioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarTipoPatrimonioOperationCompleted);
            }
            this.InvokeAsync("DeletarTipoPatrimonio", new object[] {
                        RequestTipoPatrimonio}, this.DeletarTipoPatrimonioOperationCompleted, userState);
        }
        
        private void OnDeletarTipoPatrimonioOperationCompleted(object arg) {
            if ((this.DeletarTipoPatrimonioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarTipoPatrimonioCompleted(this, new DeletarTipoPatrimonioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/AlteraTipoPatrimonio", RequestElementName="AlteraTipoPatrimonio", RequestNamespace="http://www.pece.org.br/", ResponseElementName="AlteraTipoPatrimonioResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseTipoPatrimonio", IsNullable=true)]
        public ResponseTipoPatrimonio AlterarTipoPatrimonio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestTipoPatrimonio RequestTipoPatrimonio) {
            object[] results = this.Invoke("AlterarTipoPatrimonio", new object[] {
                        RequestTipoPatrimonio});
            return ((ResponseTipoPatrimonio)(results[0]));
        }
        
        /// <remarks/>
        public void AlterarTipoPatrimonioAsync(RequestTipoPatrimonio RequestTipoPatrimonio) {
            this.AlterarTipoPatrimonioAsync(RequestTipoPatrimonio, null);
        }
        
        /// <remarks/>
        public void AlterarTipoPatrimonioAsync(RequestTipoPatrimonio RequestTipoPatrimonio, object userState) {
            if ((this.AlterarTipoPatrimonioOperationCompleted == null)) {
                this.AlterarTipoPatrimonioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarTipoPatrimonioOperationCompleted);
            }
            this.InvokeAsync("AlterarTipoPatrimonio", new object[] {
                        RequestTipoPatrimonio}, this.AlterarTipoPatrimonioOperationCompleted, userState);
        }
        
        private void OnAlterarTipoPatrimonioOperationCompleted(object arg) {
            if ((this.AlterarTipoPatrimonioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarTipoPatrimonioCompleted(this, new AlterarTipoPatrimonioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/ConsultaTipoPatrimonio", RequestElementName="ConsultaTipoPatrimonio", RequestNamespace="http://www.pece.org.br/", ResponseElementName="ConsultaTipoPatrimonioResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseTipoPatrimonio", IsNullable=true)]
        public ResponseTipoPatrimonio ConsultarTipoPatrimonio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestTipoPatrimonio RequestTipoPatrimonio) {
            object[] results = this.Invoke("ConsultarTipoPatrimonio", new object[] {
                        RequestTipoPatrimonio});
            return ((ResponseTipoPatrimonio)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarTipoPatrimonioAsync(RequestTipoPatrimonio RequestTipoPatrimonio) {
            this.ConsultarTipoPatrimonioAsync(RequestTipoPatrimonio, null);
        }
        
        /// <remarks/>
        public void ConsultarTipoPatrimonioAsync(RequestTipoPatrimonio RequestTipoPatrimonio, object userState) {
            if ((this.ConsultarTipoPatrimonioOperationCompleted == null)) {
                this.ConsultarTipoPatrimonioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarTipoPatrimonioOperationCompleted);
            }
            this.InvokeAsync("ConsultarTipoPatrimonio", new object[] {
                        RequestTipoPatrimonio}, this.ConsultarTipoPatrimonioOperationCompleted, userState);
        }
        
        private void OnConsultarTipoPatrimonioOperationCompleted(object arg) {
            if ((this.ConsultarTipoPatrimonioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarTipoPatrimonioCompleted(this, new ConsultarTipoPatrimonioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class RequestTipoPatrimonio {
        
        private TipoPatrimonio tipoPatrimonioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TipoPatrimonio TipoPatrimonio {
            get {
                return this.tipoPatrimonioField;
            }
            set {
                this.tipoPatrimonioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class TipoPatrimonio {
        
        private int idField;
        
        private string nomeField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseTipoPatrimonio))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class BaseResponse {
        
        private ResponseStatus statusCodeField;
        
        private string messageField;
        
        /// <remarks/>
        public ResponseStatus StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public enum ResponseStatus {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        NoContent,
        
        /// <remarks/>
        MovedPermanently,
        
        /// <remarks/>
        Found,
        
        /// <remarks/>
        SeeOther,
        
        /// <remarks/>
        NotModified,
        
        /// <remarks/>
        BadRequest,
        
        /// <remarks/>
        Unauthorized,
        
        /// <remarks/>
        Forbidden,
        
        /// <remarks/>
        NotFound,
        
        /// <remarks/>
        MethodNotAllowed,
        
        /// <remarks/>
        RequestTimeout,
        
        /// <remarks/>
        Conflict,
        
        /// <remarks/>
        NotImplemented,
        
        /// <remarks/>
        ServiceUnavailable,
        
        /// <remarks/>
        BadVersion,
        
        /// <remarks/>
        InternalServerError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class ResponseTipoPatrimonio : BaseResponse {
        
        private TipoPatrimonio[] listaTipoPatrimonioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TipoPatrimonio[] ListaTipoPatrimonio {
            get {
                return this.listaTipoPatrimonioField;
            }
            set {
                this.listaTipoPatrimonioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CriarTipoPatrimonioCompletedEventHandler(object sender, CriarTipoPatrimonioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CriarTipoPatrimonioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CriarTipoPatrimonioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseTipoPatrimonio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseTipoPatrimonio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void DeletarTipoPatrimonioCompletedEventHandler(object sender, DeletarTipoPatrimonioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletarTipoPatrimonioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletarTipoPatrimonioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseTipoPatrimonio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseTipoPatrimonio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void AlterarTipoPatrimonioCompletedEventHandler(object sender, AlterarTipoPatrimonioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlterarTipoPatrimonioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlterarTipoPatrimonioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseTipoPatrimonio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseTipoPatrimonio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ConsultarTipoPatrimonioCompletedEventHandler(object sender, ConsultarTipoPatrimonioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarTipoPatrimonioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarTipoPatrimonioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseTipoPatrimonio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseTipoPatrimonio)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591