//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace InterfaceUsuario.ServicoAutenticador {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicoAutenticadorSoap", Namespace="http://www.pece.org.br/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResponse))]
    public partial class ServicoAutenticador : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarPermissoesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicoAutenticador() {
            this.Url = global::InterfaceUsuario.Properties.Settings.Default.InterfaceUsuario_ServicoAutenticador_ServicoAutenticador;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event VerificarPermissoesCompletedEventHandler VerificarPermissoesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/Login", RequestNamespace="http://www.pece.org.br/", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseAutenticador", IsNullable=true)]
        public ResponseAutenticador Login([System.Xml.Serialization.XmlElementAttribute("RequestAutenticador.cs", IsNullable=true)] RequestAutenticador RequestAutenticadorcs) {
            object[] results = this.Invoke("Login", new object[] {
                        RequestAutenticadorcs});
            return ((ResponseAutenticador)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(RequestAutenticador RequestAutenticadorcs) {
            this.LoginAsync(RequestAutenticadorcs, null);
        }
        
        /// <remarks/>
        public void LoginAsync(RequestAutenticador RequestAutenticadorcs, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        RequestAutenticadorcs}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/VerificaPermissoes", RequestElementName="VerificaPermissoes", RequestNamespace="http://www.pece.org.br/", ResponseElementName="VerificaPermissoesResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseAutenticador", IsNullable=true)]
        public ResponseAutenticador VerificarPermissoes([System.Xml.Serialization.XmlElementAttribute("RequestAutenticador.cs", IsNullable=true)] RequestAutenticador RequestAutenticadorcs) {
            object[] results = this.Invoke("VerificarPermissoes", new object[] {
                        RequestAutenticadorcs});
            return ((ResponseAutenticador)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarPermissoesAsync(RequestAutenticador RequestAutenticadorcs) {
            this.VerificarPermissoesAsync(RequestAutenticadorcs, null);
        }
        
        /// <remarks/>
        public void VerificarPermissoesAsync(RequestAutenticador RequestAutenticadorcs, object userState) {
            if ((this.VerificarPermissoesOperationCompleted == null)) {
                this.VerificarPermissoesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarPermissoesOperationCompleted);
            }
            this.InvokeAsync("VerificarPermissoes", new object[] {
                        RequestAutenticadorcs}, this.VerificarPermissoesOperationCompleted, userState);
        }
        
        private void OnVerificarPermissoesOperationCompleted(object arg) {
            if ((this.VerificarPermissoesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarPermissoesCompleted(this, new VerificarPermissoesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class RequestAutenticador {
        
        private int idUsuarioField;
        
        private string senhaField;
        
        private int idTelaField;
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public int IdTela {
            get {
                return this.idTelaField;
            }
            set {
                this.idTelaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Autenticador {
        
        private bool permissaoIncluirField;
        
        private bool permissaoExcluirField;
        
        private bool permissaoConsultarField;
        
        private bool permissaoEditarField;
        
        /// <remarks/>
        public bool PermissaoIncluir {
            get {
                return this.permissaoIncluirField;
            }
            set {
                this.permissaoIncluirField = value;
            }
        }
        
        /// <remarks/>
        public bool PermissaoExcluir {
            get {
                return this.permissaoExcluirField;
            }
            set {
                this.permissaoExcluirField = value;
            }
        }
        
        /// <remarks/>
        public bool PermissaoConsultar {
            get {
                return this.permissaoConsultarField;
            }
            set {
                this.permissaoConsultarField = value;
            }
        }
        
        /// <remarks/>
        public bool PermissaoEditar {
            get {
                return this.permissaoEditarField;
            }
            set {
                this.permissaoEditarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseAutenticador))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class BaseResponse {
        
        private ResponseStatus statusCodeField;
        
        /// <remarks/>
        public ResponseStatus StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public enum ResponseStatus {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        NoContent,
        
        /// <remarks/>
        MovedPermanently,
        
        /// <remarks/>
        Found,
        
        /// <remarks/>
        SeeOther,
        
        /// <remarks/>
        NotModified,
        
        /// <remarks/>
        BadRequest,
        
        /// <remarks/>
        Unauthorized,
        
        /// <remarks/>
        Forbidden,
        
        /// <remarks/>
        NotFound,
        
        /// <remarks/>
        MethodNotAllowed,
        
        /// <remarks/>
        RequestTimeout,
        
        /// <remarks/>
        Conflict,
        
        /// <remarks/>
        NotImplemented,
        
        /// <remarks/>
        ServiceUnavailable,
        
        /// <remarks/>
        BadVersion,
        
        /// <remarks/>
        InternalServerError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class ResponseAutenticador : BaseResponse {
        
        private string messageField;
        
        private bool registroCorretoField;
        
        private Autenticador autenticadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool RegistroCorreto {
            get {
                return this.registroCorretoField;
            }
            set {
                this.registroCorretoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Autenticador Autenticador {
            get {
                return this.autenticadorField;
            }
            set {
                this.autenticadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseAutenticador Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseAutenticador)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void VerificarPermissoesCompletedEventHandler(object sender, VerificarPermissoesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarPermissoesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarPermissoesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseAutenticador Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseAutenticador)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591