//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace InterfaceUsuario.ServicoPatrimonio {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicoPatrimonioSoap", Namespace="http://www.pece.org.br/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResponse))]
    public partial class ServicoPatrimonio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CriarPatrimonioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BaixarPatrimonioOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarPatrimonioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarPatrimonioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarPatrimonioOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarManutencaoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicoPatrimonio() {
            this.Url = global::InterfaceUsuario.Properties.Settings.Default.InterfaceUsuario_ServicoPatrimonio_ServicoPatrimonio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CriarPatrimonioCompletedEventHandler CriarPatrimonioCompleted;
        
        /// <remarks/>
        public event BaixarPatrimonioCompletedEventHandler BaixarPatrimonioCompleted;
        
        /// <remarks/>
        public event DeletarPatrimonioCompletedEventHandler DeletarPatrimonioCompleted;
        
        /// <remarks/>
        public event AlterarPatrimonioCompletedEventHandler AlterarPatrimonioCompleted;
        
        /// <remarks/>
        public event ConsultarPatrimonioCompletedEventHandler ConsultarPatrimonioCompleted;
        
        /// <remarks/>
        public event RegistrarManutencaoCompletedEventHandler RegistrarManutencaoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/CriaPatrimonio", RequestElementName="CriaPatrimonio", RequestNamespace="http://www.pece.org.br/", ResponseElementName="CriaPatrimonioResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponsePatrimonio", IsNullable=true)]
        public ResponsePatrimonio CriarPatrimonio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestPatrimonio RequestPatrimonio) {
            object[] results = this.Invoke("CriarPatrimonio", new object[] {
                        RequestPatrimonio});
            return ((ResponsePatrimonio)(results[0]));
        }
        
        /// <remarks/>
        public void CriarPatrimonioAsync(RequestPatrimonio RequestPatrimonio) {
            this.CriarPatrimonioAsync(RequestPatrimonio, null);
        }
        
        /// <remarks/>
        public void CriarPatrimonioAsync(RequestPatrimonio RequestPatrimonio, object userState) {
            if ((this.CriarPatrimonioOperationCompleted == null)) {
                this.CriarPatrimonioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCriarPatrimonioOperationCompleted);
            }
            this.InvokeAsync("CriarPatrimonio", new object[] {
                        RequestPatrimonio}, this.CriarPatrimonioOperationCompleted, userState);
        }
        
        private void OnCriarPatrimonioOperationCompleted(object arg) {
            if ((this.CriarPatrimonioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CriarPatrimonioCompleted(this, new CriarPatrimonioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/BaixaPatrimonio", RequestElementName="BaixaPatrimonio", RequestNamespace="http://www.pece.org.br/", ResponseElementName="BaixaPatrimonioResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponsePatrimonio", IsNullable=true)]
        public ResponsePatrimonio BaixarPatrimonio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestPatrimonio RequestPatrimonio) {
            object[] results = this.Invoke("BaixarPatrimonio", new object[] {
                        RequestPatrimonio});
            return ((ResponsePatrimonio)(results[0]));
        }
        
        /// <remarks/>
        public void BaixarPatrimonioAsync(RequestPatrimonio RequestPatrimonio) {
            this.BaixarPatrimonioAsync(RequestPatrimonio, null);
        }
        
        /// <remarks/>
        public void BaixarPatrimonioAsync(RequestPatrimonio RequestPatrimonio, object userState) {
            if ((this.BaixarPatrimonioOperationCompleted == null)) {
                this.BaixarPatrimonioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBaixarPatrimonioOperationCompleted);
            }
            this.InvokeAsync("BaixarPatrimonio", new object[] {
                        RequestPatrimonio}, this.BaixarPatrimonioOperationCompleted, userState);
        }
        
        private void OnBaixarPatrimonioOperationCompleted(object arg) {
            if ((this.BaixarPatrimonioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BaixarPatrimonioCompleted(this, new BaixarPatrimonioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/DeletaPatrimonio", RequestElementName="DeletaPatrimonio", RequestNamespace="http://www.pece.org.br/", ResponseElementName="DeletaPatrimonioResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponsePatrimonio", IsNullable=true)]
        public ResponsePatrimonio DeletarPatrimonio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestPatrimonio RequestPatrimonio) {
            object[] results = this.Invoke("DeletarPatrimonio", new object[] {
                        RequestPatrimonio});
            return ((ResponsePatrimonio)(results[0]));
        }
        
        /// <remarks/>
        public void DeletarPatrimonioAsync(RequestPatrimonio RequestPatrimonio) {
            this.DeletarPatrimonioAsync(RequestPatrimonio, null);
        }
        
        /// <remarks/>
        public void DeletarPatrimonioAsync(RequestPatrimonio RequestPatrimonio, object userState) {
            if ((this.DeletarPatrimonioOperationCompleted == null)) {
                this.DeletarPatrimonioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarPatrimonioOperationCompleted);
            }
            this.InvokeAsync("DeletarPatrimonio", new object[] {
                        RequestPatrimonio}, this.DeletarPatrimonioOperationCompleted, userState);
        }
        
        private void OnDeletarPatrimonioOperationCompleted(object arg) {
            if ((this.DeletarPatrimonioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarPatrimonioCompleted(this, new DeletarPatrimonioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/AlteraPatrimonio", RequestElementName="AlteraPatrimonio", RequestNamespace="http://www.pece.org.br/", ResponseElementName="AlteraPatrimonioResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponsePatrimonio", IsNullable=true)]
        public ResponsePatrimonio AlterarPatrimonio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestPatrimonio RequestPatrimonio) {
            object[] results = this.Invoke("AlterarPatrimonio", new object[] {
                        RequestPatrimonio});
            return ((ResponsePatrimonio)(results[0]));
        }
        
        /// <remarks/>
        public void AlterarPatrimonioAsync(RequestPatrimonio RequestPatrimonio) {
            this.AlterarPatrimonioAsync(RequestPatrimonio, null);
        }
        
        /// <remarks/>
        public void AlterarPatrimonioAsync(RequestPatrimonio RequestPatrimonio, object userState) {
            if ((this.AlterarPatrimonioOperationCompleted == null)) {
                this.AlterarPatrimonioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarPatrimonioOperationCompleted);
            }
            this.InvokeAsync("AlterarPatrimonio", new object[] {
                        RequestPatrimonio}, this.AlterarPatrimonioOperationCompleted, userState);
        }
        
        private void OnAlterarPatrimonioOperationCompleted(object arg) {
            if ((this.AlterarPatrimonioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarPatrimonioCompleted(this, new AlterarPatrimonioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/ConsultaPatrimonio", RequestElementName="ConsultaPatrimonio", RequestNamespace="http://www.pece.org.br/", ResponseElementName="ConsultaPatrimonioResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponsePatrimonio", IsNullable=true)]
        public ResponsePatrimonio ConsultarPatrimonio([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestPatrimonio RequestPatrimonio) {
            object[] results = this.Invoke("ConsultarPatrimonio", new object[] {
                        RequestPatrimonio});
            return ((ResponsePatrimonio)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPatrimonioAsync(RequestPatrimonio RequestPatrimonio) {
            this.ConsultarPatrimonioAsync(RequestPatrimonio, null);
        }
        
        /// <remarks/>
        public void ConsultarPatrimonioAsync(RequestPatrimonio RequestPatrimonio, object userState) {
            if ((this.ConsultarPatrimonioOperationCompleted == null)) {
                this.ConsultarPatrimonioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPatrimonioOperationCompleted);
            }
            this.InvokeAsync("ConsultarPatrimonio", new object[] {
                        RequestPatrimonio}, this.ConsultarPatrimonioOperationCompleted, userState);
        }
        
        private void OnConsultarPatrimonioOperationCompleted(object arg) {
            if ((this.ConsultarPatrimonioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPatrimonioCompleted(this, new ConsultarPatrimonioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/RegistraManutencao", RequestElementName="RegistraManutencao", RequestNamespace="http://www.pece.org.br/", ResponseElementName="RegistraManutencaoResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponsePatrimonio", IsNullable=true)]
        public ResponsePatrimonio RegistrarManutencao([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestPatrimonio RequestPatrimonio) {
            object[] results = this.Invoke("RegistrarManutencao", new object[] {
                        RequestPatrimonio});
            return ((ResponsePatrimonio)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarManutencaoAsync(RequestPatrimonio RequestPatrimonio) {
            this.RegistrarManutencaoAsync(RequestPatrimonio, null);
        }
        
        /// <remarks/>
        public void RegistrarManutencaoAsync(RequestPatrimonio RequestPatrimonio, object userState) {
            if ((this.RegistrarManutencaoOperationCompleted == null)) {
                this.RegistrarManutencaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarManutencaoOperationCompleted);
            }
            this.InvokeAsync("RegistrarManutencao", new object[] {
                        RequestPatrimonio}, this.RegistrarManutencaoOperationCompleted, userState);
        }
        
        private void OnRegistrarManutencaoOperationCompleted(object arg) {
            if ((this.RegistrarManutencaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarManutencaoCompleted(this, new RegistrarManutencaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class RequestPatrimonio {
        
        private Patrimonio patrimonioField;
        
        private Manutencao manutencaoPatrimonioField;
        
        private Baixa baixaPatrimonioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Patrimonio Patrimonio {
            get {
                return this.patrimonioField;
            }
            set {
                this.patrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Manutencao ManutencaoPatrimonio {
            get {
                return this.manutencaoPatrimonioField;
            }
            set {
                this.manutencaoPatrimonioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Baixa BaixaPatrimonio {
            get {
                return this.baixaPatrimonioField;
            }
            set {
                this.baixaPatrimonioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Patrimonio {
        
        private int idEquipamentoField;
        
        private int numeroPECEField;
        
        private System.DateTime dataCompraField;
        
        private int numeroNotaFiscalField;
        
        private System.DateTime dataExpGarantiaField;
        
        private Atributo[] listAtributosField;
        
        private string caminhoFotoNotaFiscalField;
        
        private string caminhoFotoPatrimonioField;
        
        private string localPatrimonioField;
        
        private string numeroPedidoField;
        
        /// <remarks/>
        public int IdEquipamento {
            get {
                return this.idEquipamentoField;
            }
            set {
                this.idEquipamentoField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroPECE {
            get {
                return this.numeroPECEField;
            }
            set {
                this.numeroPECEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataCompra {
            get {
                return this.dataCompraField;
            }
            set {
                this.dataCompraField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroNotaFiscal {
            get {
                return this.numeroNotaFiscalField;
            }
            set {
                this.numeroNotaFiscalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataExpGarantia {
            get {
                return this.dataExpGarantiaField;
            }
            set {
                this.dataExpGarantiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ListAtributos")]
        public Atributo[] ListAtributos {
            get {
                return this.listAtributosField;
            }
            set {
                this.listAtributosField = value;
            }
        }
        
        /// <remarks/>
        public string CaminhoFotoNotaFiscal {
            get {
                return this.caminhoFotoNotaFiscalField;
            }
            set {
                this.caminhoFotoNotaFiscalField = value;
            }
        }
        
        /// <remarks/>
        public string CaminhoFotoPatrimonio {
            get {
                return this.caminhoFotoPatrimonioField;
            }
            set {
                this.caminhoFotoPatrimonioField = value;
            }
        }
        
        /// <remarks/>
        public string LocalPatrimonio {
            get {
                return this.localPatrimonioField;
            }
            set {
                this.localPatrimonioField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroPedido {
            get {
                return this.numeroPedidoField;
            }
            set {
                this.numeroPedidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Atributo {
        
        private int idField;
        
        private string nomeField;
        
        private string descricaoField;
        
        private string tipoField;
        
        private bool nuloField;
        
        private string[] listaValoresField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public bool Nulo {
            get {
                return this.nuloField;
            }
            set {
                this.nuloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ListaValores")]
        public string[] ListaValores {
            get {
                return this.listaValoresField;
            }
            set {
                this.listaValoresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponsePatrimonio))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class BaseResponse {
        
        private ResponseStatus statusCodeField;
        
        private string messageField;
        
        /// <remarks/>
        public ResponseStatus StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public enum ResponseStatus {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        NoContent,
        
        /// <remarks/>
        MovedPermanently,
        
        /// <remarks/>
        Found,
        
        /// <remarks/>
        SeeOther,
        
        /// <remarks/>
        NotModified,
        
        /// <remarks/>
        BadRequest,
        
        /// <remarks/>
        Unauthorized,
        
        /// <remarks/>
        Forbidden,
        
        /// <remarks/>
        NotFound,
        
        /// <remarks/>
        MethodNotAllowed,
        
        /// <remarks/>
        RequestTimeout,
        
        /// <remarks/>
        Conflict,
        
        /// <remarks/>
        NotImplemented,
        
        /// <remarks/>
        ServiceUnavailable,
        
        /// <remarks/>
        BadVersion,
        
        /// <remarks/>
        InternalServerError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class ResponsePatrimonio : BaseResponse {
        
        private Patrimonio[] listaPatrimonioField;
        
        /// <remarks/>
        public Patrimonio[] ListaPatrimonio {
            get {
                return this.listaPatrimonioField;
            }
            set {
                this.listaPatrimonioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Baixa {
        
        private int idBaixaField;
        
        private System.DateTime dataManutencaoField;
        
        private string destinoBaixaField;
        
        private string observacoesBaixaField;
        
        private int idUsuarioField;
        
        /// <remarks/>
        public int IdBaixa {
            get {
                return this.idBaixaField;
            }
            set {
                this.idBaixaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataManutencao {
            get {
                return this.dataManutencaoField;
            }
            set {
                this.dataManutencaoField = value;
            }
        }
        
        /// <remarks/>
        public string DestinoBaixa {
            get {
                return this.destinoBaixaField;
            }
            set {
                this.destinoBaixaField = value;
            }
        }
        
        /// <remarks/>
        public string ObservacoesBaixa {
            get {
                return this.observacoesBaixaField;
            }
            set {
                this.observacoesBaixaField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Manutencao {
        
        private int idManutencaoField;
        
        private System.DateTime dataManutencaoField;
        
        private string motivoField;
        
        private string observacaoField;
        
        private int idUsuarioField;
        
        /// <remarks/>
        public int IdManutencao {
            get {
                return this.idManutencaoField;
            }
            set {
                this.idManutencaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataManutencao {
            get {
                return this.dataManutencaoField;
            }
            set {
                this.dataManutencaoField = value;
            }
        }
        
        /// <remarks/>
        public string Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        public string Observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CriarPatrimonioCompletedEventHandler(object sender, CriarPatrimonioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CriarPatrimonioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CriarPatrimonioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponsePatrimonio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponsePatrimonio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void BaixarPatrimonioCompletedEventHandler(object sender, BaixarPatrimonioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BaixarPatrimonioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BaixarPatrimonioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponsePatrimonio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponsePatrimonio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void DeletarPatrimonioCompletedEventHandler(object sender, DeletarPatrimonioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletarPatrimonioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletarPatrimonioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponsePatrimonio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponsePatrimonio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void AlterarPatrimonioCompletedEventHandler(object sender, AlterarPatrimonioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlterarPatrimonioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlterarPatrimonioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponsePatrimonio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponsePatrimonio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ConsultarPatrimonioCompletedEventHandler(object sender, ConsultarPatrimonioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPatrimonioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPatrimonioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponsePatrimonio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponsePatrimonio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void RegistrarManutencaoCompletedEventHandler(object sender, RegistrarManutencaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarManutencaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarManutencaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponsePatrimonio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponsePatrimonio)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591